tar Wars (Sterrenoorlogen) is een Amerikaanse epische space-opera-franchise die bestaat uit een filmserie bedacht door George Lucas. In 2012 werd zijn bedrijf Lucasfilm overgenomen door de Walt Disney Company.[1]

Star Wars bestaat anno 2017 uit twee afgeronde trilogieën, één film van een geplande trilogie en een losstaande film.

De eerste twee trilogieën hebben in de loop van de jaren verschillende nabewerkingen gehad. De films samen werden genomineerd voor 25 Oscars, waarvan er tien werden gewonnen. De filmserie heeft geleid tot een media-franchise buiten de filmreeks om genaamd de Expanded Universe.

De franchise portretteert een universum dat zich afspeelt in een sterrenstelsel dat wordt omschreven als ver, ver weg. Het toont vaak de Jedi als een representatie van het goede, in strijd met de Sith, hun kwade tegenhanger. Hun wapen van keuze, het lichtzwaard, wordt algemeen erkend in de popcultuur. Het fictieve universum bevat ook veel thema's, met name invloeden van filosofie en religie. Een voorbeeld hiervan is De Kracht (The Force).
