.TH lwrap 1
.SH NAME
lwrap
.SH SYNOPSIS
.B lwrap
[-c columns] [-j columns][-e][-f text file]
.SH DESCRIPTION
Line wrap text input according to user defined line width.
.SH EXECUTION ENVIRONMENT
LANG=countrycode.utf8
.SH OPTIONS
.TP
.I "\-h"
Print usage and exit.
.TP
.I "\-c"
Set number of columns before line break.
The default is 80 (min:1,max:235).
Each three bytes glyph (e.g. CJK) takes 2 columns.
Each one or two bytes glyph (e.g. ascii and latin)
takes 1 column.
.TP
.I "\-e"
Line break without ascii space but a newline only.
The default line break is ascii space plus newline, 
this makes the output reversible back to it's original 
input format. The reason is ascii space occasionally 
been used as word and name separator in asian 
languages, and if these spaces were erased, the output 
will no longer be reversible. The default can be 
changed with this command options ,and this may be the  
desired final output.

.TP
.I "\-j"
Same as -c but justified lines with ascii spaces.
.TP
.I "\-f"
read input from text file instead of default stdin.
.TP
.I "\-d"
Output debugging text to /tmp/lwrap.debug file.
.TP
.I "\-V"
Print Version and exit.
.SH USE WITH VIM
.VE
.LP
    :[range]!lwrap -j80
    or inside file VIMRC
    set formatprg=lwrap\ -j80\

.SH AUTHORS
written by Yang Li.
.SH REPORTING BUGS
github.com/netcrop/lwrap
.SH LIMITATIONS
Many natural languages use different glyph width within the same font,
the output line width may not be consistent in these languages.
.SH LICENSE
GNU GENERAL PUBLIC LICENSE Version 2

.SH EXAMPLES
.VE
.LP
  The  franchise  began  in 1977 	実写映画本編
  with  the  release of the film 	本シリーズの実写映画本編は、複
  Star   Wars  (later  subtitled 	数のエピソードにより綴られるサ
  Episode  IV:  A  New  Hope  in 	ーガの形式を採っている。エピソ
  1981),[2][3]  which  became  a 	ード番号は、原題ではローマ数字
  worldwide      pop     culture 	を採用しているが、邦題ではアラ
  phenomenon. It was followed by 	ビア数字を採用している。
  the   successful  sequels  The 	映画が『エピソード1/ファントム
  Empire Strikes Back (1980) and 	・メナス』からではなく『エピソ
  Return  of  the  Jedi  (1983); 	ード4/新たなる希望』から制作さ
  these  three  films constitute 	れたのは、まずは一作目が商業的
  the    original    Star   Wars 	に成果を収めねばシリーズ化が望
  trilogy. A prequel trilogy was 	めず、更に一番“冒険活劇”とし
  released   between   1999  and 	ての完成度の高かった『エピソー
  2005,   which  received  mixed 	ド4/新たなる希望』を最初に世に
  reactions  from  both  critics 	出すことが得策だったためである
  and  fans.  A  sequel  trilogy 	。また『エピソード1・2・3』の
  began in 2015 with the release 	時代は、全銀河の首都である大都
  of   Star   Wars:   The  Force 	市惑星コルサントの描写や、銀河
  Awakens.  All seven films were 	共和国と独立星系連合の間で勃発

  De  franchise portretteert een 	《星球大战》（英语：Star  Wars
  universum dat zich afspeelt in 	），中文可簡稱「星戰」，是美國
  een  sterrenstelsel  dat wordt 	導演兼編劇乔治·卢卡斯所構思拍
  omschreven  als  ver, ver weg. 	攝的一系列科幻電影。同时“星球
  Het toont vaak de Jedi als een 	大戰”也是该系列電影最早拍摄上
  representatie  van  het goede, 	映的第四章故事的原始片名。
  in  strijd  met  de  Sith, hun 	从1970年代末到1980年代，盧卡斯
  kwade  tegenhanger.  Hun wapen 	出品了《星際大戰》三部曲。他曾
  van  keuze,  het  lichtzwaard, 	説明第一部星戰（第四部曲）的人
  wordt  algemeen  erkend  in de 	物及故事是參照日本導演黑澤明的
  popcultuur.    Het    fictieve 	《戰國英豪》（隠し砦の三悪人）
  universum   bevat   ook   veel 	所創作而成；原三部曲以二戰英德
  thema's,  met  name  invloeden 	大戰為架構並溶入美國西部片及日
  van  filosofie en religie. Een 	本武士刀劇的節奏；藴涵了太空冒
  voorbeeld hiervan is De Kracht 	險、希臘神話的大視野制作。影片

  Star  Wars (à l'origine nommée 	《스타워즈》(Star  Wars),  재개
  sous  son  titre  français, La 	봉 제목 《스타워즈 에피소드 4: 
  Guerre  des  étoiles)  est  un 	새로운  희망》(Star  Wars 
  univers   fantastique   et  de 	Episode  IV:  A New Hope)은 1977
  science-fiction    créé    par 	년  미국에서  제작된 SF 에픽 스
  George  Lucas.  D'abord conçue 	페이스  오페라  영화이다. 조지 
  comme       une       trilogie 	루카스가 감독과 각본을 맡았다. 
  cinématographique sortie entre 	《스타  워즈》  오리지널 삼부작 
  1977    et   1983,   la   saga 	중  가장 처음 만들어진 작품이며
  s'élargit   ensuite  de  trois 	,  시나리오  상으로는 4번째 에피
  nouveaux  films  entre 1999 et 	소드에  해당한다.  마크 해밀, 해
  2005,  narrant  des événements 	리슨  포드,  캐리 피셔, 피터 커
  antérieurs   à   la   première 	싱,  앨릭  기니스, 데이비드 프로
  trilogie.    Cette    dernière 	스,  제임스  얼 존스, 앤서니 대
  (épisodes  IV,  V et VI) ainsi 	니얼스,  케니  베이커, 피터 메이
